### ISSUE TITLE
Timer not always vibrate when Watch is in deep sleep

### ISSUE THREAD

**Issue by 2Belette** [AsteroidOS/asteroid-timer#3]
After the time due the watch is not vibrating.
Waking up the watch in touching it and then the vibration is done.

Test made with a 15minutes timer

**Comment by FlorentRevest** [comment]
After several experiments with solutions based on libiphb, timed and systemd timers (e.g: https://github.com/AsteroidOS/asteroid-timer/commit/938db420dabeb7312eec266183487b0961ad6fb5) I have been led to the conclusion that blocking deep sleep when a timer is running would be the best (least worst?) solution for a correct behavior. This issue should then be "fixed" by https://github.com/AsteroidOS/asteroid-timer/commit/c6ceead8052075dd5ff55f7dae0704edc875ff1b
