### ISSUE TITLE
Better alert?

### ISSUE THREAD

**Issue by KorakSilvercloud** [AsteroidOS/asteroid-timer#4]
The timer only gives one short buzz when time runs out. I feel this would be better if changed to instead pulse until dismissed similar to how the alarm app behaves.

**Comment by FlorentRevest** [comment]
Feedback in AsteroidOS is handled by the "Non Graphical Feedback Daemon": ngfd. Apps use this daemon using the NonGraphicalFeedback QML element. The type of notification (and vibration) is defined in the "event" field. One should copy the event name used in asteroid-alarmpresenter onto the one used in asteroid-timer.
